### ISSUE TITLE
[ documentation ] Comparision to loco

### ISSUE THREAD

**Issue by yonas** [levkk/rwf#5]
How does this compare to [loco](https://loco.rs/)?

**Comment by levkk** [comment]
I think this may be out of scope for our documentation. Comparing tools to each other is best done by their users, not their authors.

**Comment by yonas** [comment]
You don't want to sell me on rwf? Why should I bother using this project when loco does such a good job.

**Comment by NoelJacob** [comment]
>  Comparing tools to each other is best done by their users, not their authors.

It would definiately be beneficial to users if you know loco too. Many other tools do it right in the README. But that's my personal opinion. Also, Thank you for making and maintanig rwf ⬆️❤️
